2025-02-12 14:06:25,530 [ERROR] Erreur chargement networks.json: [Errno 2] No such file or directory: 'config\\networks.json'
2025-02-12 14:06:25,530 [ERROR] Erreur de chargement mÃ©moire : 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2025-02-12 14:06:25,531 [ERROR] Erreur de chargement mÃ©moire : 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2025-02-12 14:06:25,532 [INFO] logging in using static token
2025-02-12 14:06:26,722 [INFO] Shard ID None has connected to Gateway (Session ID: 0417ba7e681aaf35253c4f0333884bbb).
2025-02-12 14:06:28,746 [INFO] 
----------------------------------------
2025-02-12 14:06:28,748 [INFO]       T7STEAM - The Shader AI Bot       
2025-02-12 14:06:28,748 [INFO]        Version 7.3 | Greeny CORE        
2025-02-12 14:06:28,748 [INFO] ----------------------------------------
2025-02-12 14:06:28,748 [INFO] ConnectÃ© en tant que SHADEBOT
2025-02-12 14:06:28,749 [INFO] ID: 1323015323233812525
2025-02-12 14:06:28,749 [INFO] Serveurs: 2
2025-02-12 14:06:28,749 [INFO] ----------------------------------------
2025-02-12 14:10:22,518 [ERROR] Erreur chargement networks.json: [Errno 2] No such file or directory: 'config\\networks.json'
2025-02-12 14:10:22,519 [ERROR] Erreur de chargement mÃ©moire : Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
2025-02-12 14:10:22,519 [ERROR] Erreur de chargement mÃ©moire : Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
2025-02-12 14:10:22,520 [INFO] logging in using static token
2025-02-12 14:10:25,030 [INFO] Shard ID None has connected to Gateway (Session ID: a670c68e11179a0011e0eb869de8393b).
2025-02-12 14:10:27,135 [INFO] 
----------------------------------------
2025-02-12 14:10:27,135 [INFO]       T7STEAM - The Shader AI Bot       
2025-02-12 14:10:27,135 [INFO]        Version 7.3 | Greeny CORE        
2025-02-12 14:10:27,136 [INFO] ----------------------------------------
2025-02-12 14:10:27,136 [INFO] ConnectÃ© en tant que SHADEBOT
2025-02-12 14:10:27,136 [INFO] ID: 1323015323233812525
2025-02-12 14:10:27,136 [INFO] Serveurs: 2
2025-02-12 14:10:27,136 [INFO] ----------------------------------------
2025-02-12 14:18:04,866 [ERROR] Erreur chargement networks.json: [Errno 2] No such file or directory: 'config\\networks.json'
2025-02-12 14:18:04,867 [ERROR] Erreur de chargement mÃ©moire : Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
2025-02-12 14:18:04,867 [ERROR] Erreur de chargement mÃ©moire : Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
2025-02-12 14:18:04,869 [INFO] logging in using static token
2025-02-12 14:18:05,823 [INFO] Shard ID None has connected to Gateway (Session ID: 85c70371f3a76ef78148d8cfba1e2504).
2025-02-12 14:18:07,855 [INFO] 
----------------------------------------
2025-02-12 14:18:07,856 [INFO]       T7STEAM - The Shader AI Bot       
2025-02-12 14:18:07,856 [INFO]        Version 7.3 | Greeny CORE        
2025-02-12 14:18:07,856 [INFO] ----------------------------------------
2025-02-12 14:18:07,856 [INFO] ConnectÃ© en tant que SHADEBOT
2025-02-12 14:18:07,856 [INFO] ID: 1323015323233812525
2025-02-12 14:18:07,856 [INFO] Serveurs: 2
2025-02-12 14:18:07,857 [INFO] ----------------------------------------
2025-02-12 14:26:22,827 [ERROR] Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "ask" is not found
2025-02-12 15:06:06,844 [ERROR] Erreur chargement networks.json: Expecting value: line 1 column 1 (char 0)
2025-02-12 15:06:06,844 [ERROR] Erreur de chargement mémoire : Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
2025-02-12 15:06:06,846 [INFO] logging in using static token
2025-02-12 15:06:06,846 [ERROR] Erreur au démarrage du bot: expected token to be a str, received NoneType instead
2025-02-12 15:10:53,871 [ERROR] Erreur chargement networks.json: Expecting value: line 1 column 1 (char 0)
2025-02-12 15:10:53,872 [ERROR] Erreur de chargement mémoire : Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
2025-02-12 15:10:53,873 [INFO] logging in using static token
2025-02-12 15:10:53,874 [ERROR] Erreur au démarrage du bot: expected token to be a str, received NoneType instead
2025-02-12 16:15:32,889 [ERROR] Erreur chargement networks.json: Expecting value: line 1 column 1 (char 0)
2025-02-12 16:15:32,890 [ERROR] Erreur de chargement mémoire : Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
2025-02-12 16:15:32,891 [INFO] logging in using static token
2025-02-12 16:15:34,088 [INFO] Shard ID None has connected to Gateway (Session ID: 85615de20bc39269db8b061217d7409a).
2025-02-12 16:15:36,116 [INFO] 
----------------------------------------
2025-02-12 16:15:36,116 [INFO]        T7STEAM - The Shader AI Bot
2025-02-12 16:15:36,117 [INFO]         Version 7.3 | Greeny CORE
2025-02-12 16:15:36,117 [INFO] ----------------------------------------
2025-02-12 16:15:36,117 [INFO] Connecté en tant que SHADEBOT
2025-02-12 16:15:36,117 [INFO] ID: 1323015323233812525
2025-02-12 16:15:36,117 [INFO] Serveurs: 2
2025-02-12 16:15:36,117 [INFO] ----------------------------------------
2025-02-12 16:16:26,120 [ERROR] Erreur Venice: 200, message='Attempt to decode JSON with unexpected mimetype: text/json', url='https://api.venice.ai/api/v1/chat/completions'
2025-02-12 16:17:34,818 [ERROR] Erreur Venice: 200, message='Attempt to decode JSON with unexpected mimetype: text/json', url='https://api.venice.ai/api/v1/chat/completions'
2025-02-12 16:17:57,851 [ERROR] Erreur Venice: 200, message='Attempt to decode JSON with unexpected mimetype: text/json', url='https://api.venice.ai/api/v1/chat/completions'
2025-02-12 17:19:39,917 [ERROR] Erreur chargement networks: Expecting value: line 1 column 1 (char 0)
2025-02-12 17:19:39,917 [ERROR] Erreur de chargement mémoire : Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
2025-02-12 17:19:39,919 [INFO] logging in using static token
2025-02-12 17:19:41,137 [INFO] Shard ID None has connected to Gateway (Session ID: 9a817b7a334290fb48fa476090ae21bb).
2025-02-12 17:19:43,243 [INFO] 
----------------------------------------
2025-02-12 17:19:43,243 [INFO]        T7STEAM - The Shader AI Bot
2025-02-12 17:19:43,243 [INFO]         Version 7.3 | Greeny CORE
2025-02-12 17:19:43,244 [INFO] ----------------------------------------
2025-02-12 17:19:43,244 [INFO] Connecté en tant que SHADEBOT
2025-02-12 17:19:43,244 [INFO] ID: 1323015323233812525
2025-02-12 17:19:43,244 [INFO] Serveurs: 2
2025-02-12 17:19:43,244 [INFO] ----------------------------------------
2025-02-12 17:22:12,222 [ERROR] Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "lang" is not found
2025-02-12 17:32:43,174 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 494, in finish_recv
    return ov.getresult()
           ^^^^^^^^^^^^^^
OSError: [WinError 64] Le nom réseau spécifié n’est plus disponible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
             ^^^^^^^^^^^^
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 854, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 498, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] Le nom réseau spécifié n’est plus disponible

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\BIG GREEN 2025 V01\t7steam-core\t7steam-c1-shadebot\shaderbot_greeny_v7.3.py", line 243, in on_message
    await message.channel.send(response)
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\abc.py", line 1538, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1425, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 730, in _request
    await resp.start(conn)
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 1059, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fatid\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\streams.py", line 671, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 64] Le nom réseau spécifié n’est plus disponible
2025-02-12 18:04:00,346 [ERROR] Erreur chargement networks: Expecting value: line 1 column 1 (char 0)
2025-02-12 18:04:00,355 [INFO] logging in using static token
2025-02-12 18:04:01,876 [INFO] Shard ID None has connected to Gateway (Session ID: 734fe92baeecc386753a5129be5158b7).
2025-02-12 18:04:03,884 [INFO] 
----------------------------------------
2025-02-12 18:04:03,884 [INFO]        T7STEAM - The Shader AI Bot
2025-02-12 18:04:03,885 [INFO]         Version 7.3 | Greeny CORE
2025-02-12 18:04:03,885 [INFO] ----------------------------------------
2025-02-12 18:04:03,885 [INFO] Connecté en tant que SHADEBOT
2025-02-12 18:04:03,885 [INFO] ID: 1323015323233812525
2025-02-12 18:04:03,885 [INFO] Serveurs: 2
2025-02-12 18:04:03,885 [INFO] ----------------------------------------
2025-02-12 18:19:18,474 [ERROR] Erreur chargement networks: Expecting value: line 1 column 1 (char 0)
2025-02-12 18:19:18,476 [INFO] logging in using static token
2025-02-12 18:19:19,429 [INFO] Shard ID None has connected to Gateway (Session ID: 0602c9be02e66c2aa201d350e5bf41b2).
2025-02-12 18:19:21,466 [INFO] 
----------------------------------------
2025-02-12 18:19:21,466 [INFO]        T7STEAM - The Shader AI Bot
2025-02-12 18:19:21,466 [INFO]         Version 7.3 | Greeny CORE
2025-02-12 18:19:21,467 [INFO] ----------------------------------------
2025-02-12 18:19:21,467 [INFO] Connecté en tant que SHADEBOT
2025-02-12 18:19:21,467 [INFO] ID: 1323015323233812525
2025-02-12 18:19:21,467 [INFO] Serveurs: 2
2025-02-12 18:19:21,467 [INFO] ----------------------------------------
2025-02-12 18:24:45,349 [ERROR] Erreur chargement networks: Expecting value: line 1 column 1 (char 0)
2025-02-12 18:24:45,350 [INFO] logging in using static token
2025-02-12 18:24:46,429 [INFO] Shard ID None has connected to Gateway (Session ID: 878ddd70c8aa92043ffa9313a37ce98f).
2025-02-12 18:24:48,457 [INFO] 
----------------------------------------
2025-02-12 18:24:48,457 [INFO]        T7STEAM - The Shader AI Bot
2025-02-12 18:24:48,457 [INFO]         Version 7.3 | Greeny CORE
2025-02-12 18:24:48,458 [INFO] ----------------------------------------
2025-02-12 18:24:48,458 [INFO] Connecté en tant que SHADEBOT
2025-02-12 18:24:48,458 [INFO] ID: 1323015323233812525
2025-02-12 18:24:48,458 [INFO] Serveurs: 2
2025-02-12 18:24:48,458 [INFO] ----------------------------------------
2025-02-12 19:26:48,989 [INFO] Shard ID None has successfully RESUMED session 878ddd70c8aa92043ffa9313a37ce98f.
